start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 000/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 001/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 002/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 003/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 004/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 005/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 006/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 007/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 008/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 009/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 019/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 021/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 027/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 031/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 037/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 056/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 069/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 085/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 254/top
start C:\altera\13.0sp1\quartus\bin\quartus_sh --flow compile 255/top
